name: qed_app_thinkit
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_icon_button: ^1.0.2
  animated_toggle_switch: ^0.6.2
  clipboard: ^0.1.3
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.5
  cupertino_modal_sheet: ^1.0.0
  cupertino_progress_bar: ^0.2.0
  expandable_widgets: ^1.0.3+1
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.16
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_clipboard_manager: ^0.0.2
  flutter_slidable: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  geolocator: ^9.0.2
  get: 4.6.5
  html: ^0.15.2
  http: ^0.13.5
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+1
  interactiveviewer_gallery: ^0.6.0
  intl: ^0.18.0
  inview_notifier_list: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre
  modal_progress_hud_nsn: ^0.3.0
  page_transition: ^2.0.9
  pull_to_refresh: ^2.0.0
  reorderables: ^0.6.0
  table_calendar: ^3.0.9
  tabler_icons: ^2.5.0+1
  transition: ^2.0.2
  typewritertext: ^1.8.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "ThinKit"

flutter:
  uses-material-design: true

  #assets/images & gifs
  assets:
    - assets/images/
    - assets/gifs/
fonts:
  - family: SFPro
    fonts:
      - asset: assets/fonts/SF-Pro.ttf

  - family: SFProDisplay
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Ultralight.ttf
        weight: 100
      - asset: assets/fonts/SF-Pro-Display-Thin.ttf
        weight: 200
      - asset: assets/fonts/SF-Pro-Display-Light.ttf
        weight: 300
      - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        weight: 400
      - asset: assets/fonts/SF-Pro-Display-Medium.ttf
        weight: 500
      - asset: assets/fonts/SF-Pro-Display-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/SF-Pro-Display-Bold.ttf
        weight: 700
      - asset: assets/fonts/SF-Pro-Display-Heavy.ttf
        weight: 800
      - asset: fonts/SF-Pro-Display-Black.ttf
        weight: 900

  - family: SFProText
    fonts:
      - asset: assets/fonts/SF-Pro-Text-Ultralight.ttf
        weight: 100
      - asset: assets/fonts/SF-Pro-Text-Thin.ttf
        weight: 200
      - asset: assets/fonts/SF-Pro-Text-Light.ttf
        weight: 300
      - asset: assets/fonts/SF-Pro-Text-Regular.ttf
        weight: 400
      - asset: assets/fonts/SF-Pro-Text-Medium.ttf
        weight: 500
      - asset: assets/fonts/SF-Pro-Text-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/SF-Pro-Text-Bold.ttf
        weight: 700
      - asset: assets/fonts/SF-Pro-Text-Heavy.ttf
        weight: 800
      - asset: fonts/SF-Pro-Text-Black.ttf
        weight: 900
